name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Mod
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: v3.0.0-beta.1
          # This tells the builder where the SDK was installed
          sdk-path: ${{ env.GEODE_SDK }}
          combine: true
          # Points to your folder containing CMakeLists.txt
          path: src/geode
